; PlatformIO — Seguidor + Ponto Verde OBR 2026 (ESP32)
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
    pololu/QTRSensors               ; seguimento de linha (analog)
    electroniccats/MPU6050          ; giroscópio (giro controlado)
    adafruit/Adafruit TCS34725      ; sensores de cor
