; PlatformIO Project — Seguidor de Linha + Ponto Verde (ESP32)
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps =
    andrealombardo/L298N@^2.0.3
    pololu/QTRSensors@^4.0.0
    adafruit/Adafruit TCS34725@^1.4.4
